export ZSH="/home/orcola/.oh-my-zsh"
ZSH_THEME="norm"
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export ANDROID_HOME=~/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:~/android-studio/bin
alias onv="source venv/bin/activate"
alias mkvenv="python3 -m venv venv"
alias pyv="python3 -m venv venv && source venv/bin/activate"
alias android-dev="studio.sh"
